apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    visualize: "true"
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: web
        visualize: "true"
    spec:
      containers:
      - name: sukie
        image: gcr.io/${PROJECT}/sukie:0.1
        ports:
        - containerPort: 8080