apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v1
  version: v1
spec:
  replicas: 5
  selector:
    role: web
    version: v1
  template:
    metadata:
      labels:
        role: web
        version: v1
    spec:
      containers:
      - name: sukie
        image: gcr.io/connect-js/sukie:0.1
        ports:
        - containerPort: 8080