apiVersion: v1
kind: ReplicationController
metadata:
  name: web-v1
  labels:
    version: v1
    visualize: "true"
spec:
  replicas: 3
  selector:
    role: web
    version: v1
  template:
    metadata:
      labels:
        role: web
        version: v1
        visualize: "true"
    spec:
      containers:
      - name: sukie
        image: gcr.io/${PROJECT}/sukie:0.1
        ports:
        - containerPort: 8080